// <auto-generated />
namespace Onyx.Cartographer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedFieldsToRequiredInUserModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedFieldsToRequiredInUserModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201308012332355_AddedFieldsToRequiredInUserModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
