// <auto-generated />
namespace Onyx.Cartographer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RemovedRequireAttributeOnEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovedRequireAttributeOnEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "201308011352537_RemovedRequireAttributeOnEmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
