// <auto-generated />
namespace Onyx.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Sessions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sessions));
        
        string IMigrationMetadata.Id
        {
            get { return "201307202137277_Sessions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
